### ISSUE TITLE
Other icon fonts

### ISSUE THREAD

**Issue by brianteeman** [yireo/plg_system_fontawesome#2]
I have started to use flaticon.com on a lot of projects to build my own icon font libraries for use on sites. It would be awesome if this plugin could be used for that (I know I could just fork it but its always nice to share)

This would require : 
1. Load locally instead of from the cdn and a field to enter the path
2. Customise the prefix so you can use something other than "fa"

**Comment by yireo** [comment]
See the other issue on point 1 - has been added. There is now also a prefix field to replace the prefix "fa" with something else.
